# Generated by Django 5.0 on 2026-03-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('issued', 'issued'), ('returned', 'returned'), ('restocked', 'restocked'), ('requested', 'requested'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Activity entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
