# Generated by Django 5.0 on 2026-04-02 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_timestamp_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
