# Generated by Django 5.2.12 on 2026-04-05 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('query', 'Natural Language Query'), ('insight', 'Generated Insight'), ('simulation', 'Reorder Simulation')], max_length=16)),
                ('user_input', models.TextField(blank=True)),
                ('context_summary', models.TextField(blank=True)),
                ('full_prompt', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('response_data', models.JSONField(default=dict)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('stockout_risk', 'Stockout Risk'), ('overstock', 'Overstock'), ('demand_trend', 'Demand Trend'), ('supplier_risk', 'Supplier Risk'), ('cost_optimization', 'Cost Optimization'), ('operational', 'Operational')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='active', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('impact_estimate', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('related_item_ids', models.JSONField(default=list)),
                ('related_supplier_ids', models.JSONField(default=list)),
                ('feedback', models.CharField(blank=True, max_length=16)),
                ('feedback_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiinteraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('reorder', 'Reorder'), ('rebalance', 'Rebalance Inventory'), ('decommission', 'Decommission Dead Stock')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], db_index=True, default='pending', max_length=16)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiinteraction')),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.insightrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_prompt', models.TextField()),
                ('user_template', models.TextField(help_text='Use {variable} placeholders.')),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('max_tokens', models.PositiveIntegerField(default=1024)),
                ('temperature', models.FloatField(default=0.3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug', '-version'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='prompt_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.prompttemplate'),
        ),
        migrations.AddIndex(
            model_name='insightrecord',
            index=models.Index(fields=['category', 'severity', 'status'], name='ai_insightr_categor_0ce67f_idx'),
        ),
    ]
