# Generated by Django 5.0 on 2026-04-06 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_key', models.CharField(max_length=128, unique=True)),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source', 'chunk_key'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='ai_knowledg_source_ecc5d8_idx')],
            },
        ),
    ]
