from django.db import models
from django.utils import timezone


class RiskScore(models.Model):
    """Computed risk score for an inventory item or supplier."""
    RISK_TYPES = [
        ('stockout', 'Stockout Risk'),
        ('overstock', 'Overstock Risk'),
        ('supplier_delay', 'Supplier Delay Risk'),
        ('demand_spike', 'Demand Spike'),
    ]
    risk_type = models.CharField(max_length=20, choices=RISK_TYPES, db_index=True)
    item = models.ForeignKey('inventory.InventoryItem', on_delete=models.CASCADE, null=True, blank=True, related_name='risk_scores')
    supplier = models.ForeignKey('suppliers.Supplier', on_delete=models.CASCADE, null=True, blank=True, related_name='risk_scores')
    score = models.FloatField(help_text='0.0 (no risk) to 1.0 (certain)')
    factors = models.JSONField(default=dict)
    computed_at = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        ordering = ['-score', '-computed_at']
        indexes = [
            models.Index(fields=['risk_type', 'score']),
        ]

    def __str__(self):
        target = self.item.name if self.item else (self.supplier.name if self.supplier else '?')
        return f'{self.risk_type}: {target} = {self.score:.2f}'


class Alert(models.Model):
    """Prioritized alert generated by the risk engine."""
    SEVERITY_CHOICES = [
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('critical', 'Critical'),
    ]
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('acknowledged', 'Acknowledged'),
        ('resolved', 'Resolved'),
        ('dismissed', 'Dismissed'),
    ]
    title = models.CharField(max_length=255)
    message = models.TextField()
    severity = models.CharField(max_length=16, choices=SEVERITY_CHOICES, db_index=True)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default='active', db_index=True)
    alert_type = models.CharField(max_length=32, db_index=True)
    item = models.ForeignKey('inventory.InventoryItem', on_delete=models.CASCADE, null=True, blank=True, related_name='alerts')
    supplier = models.ForeignKey('suppliers.Supplier', on_delete=models.CASCADE, null=True, blank=True, related_name='alerts')
    risk_score = models.ForeignKey(RiskScore, on_delete=models.SET_NULL, null=True, blank=True)
    details = models.JSONField(default=dict)
    created_at = models.DateTimeField(default=timezone.now, db_index=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['severity', 'status']),
        ]

    def __str__(self):
        return f'[{self.severity}] {self.title}'
