# Generated by Django 5.2.12 on 2026-04-05 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_min_threshold_and_more'),
        ('suppliers', '0002_alter_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_items', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('low_stock_count', models.IntegerField(default=0)),
                ('out_of_stock_count', models.IntegerField(default=0)),
                ('overdue_borrows', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('avg_supplier_rating', models.FloatField(default=0)),
                ('inventory_turnover_rate', models.FloatField(default=0)),
                ('fill_rate', models.FloatField(default=0)),
                ('health_score', models.FloatField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_requested', models.IntegerField(default=0)),
                ('total_issued', models.IntegerField(default=0)),
                ('total_returned', models.IntegerField(default=0)),
                ('unique_requestors', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('item', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('issue', 'Issue'), ('return', 'Return'), ('restock', 'Restock'), ('adjustment', 'Adjustment')], db_index=True, max_length=16)),
                ('quantity_delta', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=32)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item', 'timestamp'], name='analytics_i_item_id_213be8_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('quantity', models.IntegerField()),
                ('min_threshold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=32)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date', 'category'], name='analytics_i_snapsho_cf0350_idx')],
                'unique_together': {('item', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('items_supplied_count', models.IntegerField(default=0)),
                ('avg_lead_time_days', models.FloatField(blank=True, null=True)),
                ('on_time_delivery_pct', models.FloatField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rating_snapshot', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('supplier', 'period_start')},
            },
        ),
    ]
