# Generated by Django 5.0 on 2026-03-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Tools', 'Tools'), ('Consumables', 'Consumables')], max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('min_threshold', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
