# Generated by Django 5.0 on 2026-04-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowed', '0001_initial'),
        ('inventory', '0002_alter_inventoryitem_min_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borroweditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_records', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='borroweditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
